package su.nightexpress.ama.api.arena.game;

public enum ArenaGameEventType {
    GAME_START, GAME_END_WIN, GAME_END_LOSE, GAME_END_TIME,
    WAVE_START, WAVE_END,
    SHOP_ITEM_UNLOCKED, SHOP_ITEM_LOCKED,
    PLAYER_JOIN, PLAYER_LEAVE, PLAYER_DEATH,
    MOB_KILLED,
    SCORE_INCREASED, SCORE_DECREASED,
    REGION_LOCKED, REGION_UNLOCKED,
    SPOT_CHANGED,
}
