Title: '&8&l「 &9Arena Shop Product List &8&l」'
Size: 54

Object:
  Slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
  Name: '&eProduct: &6%shop_product_name% &7(&f%shop_product_id%&7)'
  Lore:
    - '&bPrice: &a%shop_product_price%'
    - '&7'
    - '&6Left-Click: &eEdit'
    - '&6Shift+Right: &eDelete &7(No Undo)'

Content:
  page_next:
    Display:
      default:
        Item:
          material: ENDER_EYE
          name: '&e&lNext Page →'
    Slots: 44
    Type: PAGE_NEXT
  page_previous:
    Display:
      default:
        Item:
          material: ENDER_EYE
          name: '&e&l← Previous Page'
    Slots: 36
    Type: PAGE_PREVIOUS
  return:
    Display:
      default:
        Item:
          material: BARRIER
          name: '&c&lReturn &4✕'
    Slots: 39
    Type: RETURN

Editor:
  create:
    Display:
      default:
        Item:
          material: ANVIL
          name: '&a&lNew Product &2&l+'
    Slots: 41
    Type: SHOP_PRODUCT_CREATE