Title: '&8&l「 &9Arena Reward Settings &8&l」'
Size: 36

Content:
  return:
    Display:
      default:
        Item:
          material: BARRIER
          name: '&c&lReturn &4✕'
    Slots: 31
    Type: RETURN

Editor:
  triggers:
    Display:
      default:
        Item:
          material: CLOCK
          name: '&eGame Triggers'
          lore:
            - '&bThis reward will be given'
            - '&bto target player(s) on the'
            - '&bfollowing arena events:'
            - '%arena_game_triggers%'
            - '&7'
            - '&dFor more details about the triggers,'
            - '&dplease visit: &bhttp://nexwiki.info'
            - '&7'
            - '&6Left-Click: &eAdd Trigger'
            - '&6Right-Click: &eRemove All'
    Slots: 13
    Type: REWARD_CHANGE_TRIGGERS

  name:
    Display:
      default:
        Item:
          material: NAME_TAG
          name: '&eReward Name'
          lore:
            - '&bCurrent: &a%reward_name%'
            - '&7'
            - '&7Reward name will be used when player'
            - '&7gets a notification about recived reward(s).'
            - '&7'
            - '&6Left-Click: &eChange'
    Slots: 10
    Type: REWARD_CHANGE_NAME

  islate:
    Display:
      default:
        Item:
          material: IRON_DOOR
          name: '&eLate Reward'
          lore:
            - '&bCurrent: &a%reward_is_late%'
            - '&7'
            - '&7Late rewards will be given when'
            - '&7player leaves the arena. Otherwise,'
            - '&7it will be given instantly.'
            - '&7'
            - '&6Left-Click: &eToggle'
    Slots: 11
    Type: REWARD_CHANGE_LATE

  target:
    Display:
      default:
        Item:
          material: ARMOR_STAND
          name: '&eTarget Type'
          lore:
            - '&bCurrent: &a%reward_target_type%'
            - '&7'
            - '&7Defines, which player(s) will obtain'
            - '&7this reward during the game.'
            - '&7'
            - '&6Left-Click: &eChange'
    Slots: 12
    Type: REWARD_CHANGE_TARGET_TYPE

  chance:
    Display:
      default:
        Item:
          material: COMPARATOR
          name: '&eChance'
          lore:
            - '&bCurrent: &a%reward_chance%%'
            - '&7'
            - '&7Defines a chance this reward will'
            - '&7be given at all.'
            - '&7'
            - '&6Left-Click: &eChange'
    Slots: 14
    Type: REWARD_CHANGE_CHANCE

  commands:
    Display:
      default:
        Item:
          material: COMMAND_BLOCK
          name: '&eCommands'
          lore:
            - '&bThe following commands will be'
            - '&bexecuted when reward is given:'
            - '&a%reward_commands%'
            - '&7'
            - '&6Left-Click: &eAdd Command'
            - '&6Right-Click: &eClear'
    Slots: 15
    Type: REWARD_CHANGE_COMMANDS

  items:
    Display:
      default:
        Item:
          material: CHEST
          name: '&eItems'
          lore:
            - '&bHere you can add items that will'
            - '&bbe given to player(s) when they'
            - '&bobtain this reward.'
            - '&7'
            - '&aSimply put/take items in/from the chest'
            - '&athat will be opened, then use ESC'
            - '&ato return back to here.'
            - '&7'
            - '&6Left-Click: &eNavigate'
    Slots: 16
    Type: REWARD_CHANGE_ITEMS